import pg from "pg";
const client = new pg.Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
await client.connect();
const ev = await client.query("SELECT id, event, success, error, payload, created_at FROM telegram_notification_events ORDER BY id DESC LIMIT 10");
console.log("=== NOTIF EVENTS ===");
for (const r of ev.rows) console.log(JSON.stringify(r));
const pay = await client.query("SELECT id, order_id, status, created_at FROM payments ORDER BY id DESC LIMIT 5");
console.log("=== PAYMENTS ===");
for (const r of pay.rows) console.log(JSON.stringify(r));
const actions = await client.query("SELECT id, action, result, reason FROM telegram_admin_actions ORDER BY id DESC LIMIT 5");
console.log("=== ADMIN ACTIONS ===");
for (const r of actions.rows) console.log(JSON.stringify(r));
await client.end();
