# ---- Build stage ----
FROM node:24-slim AS build
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9.15.0 --activate
COPY . .
ENV NODE_ENV=production
# Frozen lockfile: deterministic install matching the committed pnpm-lock.yaml
# (regenerated by pnpm@9.15.0). Never delete the lockfile here — a fresh resolve
# can fail on the workspace's minimumReleaseAge=1440 guard and pulls latest versions.
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @workspace/razr-agency run build
RUN pnpm --filter @workspace/api-server run build

# ---- Runtime stage ----
# Single container serving both the API (Express, bundle in dist/index.mjs) and
# the built SPA (dist/public). Requires env: DATABASE_URL, JWT_SECRET, PORT.
FROM node:24-slim
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
COPY --from=build /app/artifacts/api-server/dist ./dist
COPY --from=build /app/artifacts/razr-agency/dist/public ./dist/public
EXPOSE 3000
# Bootstrap the database schema + optional SUPER_ADMIN seed before starting the API
CMD ["sh", "-c", "node dist/bootstrap-db.mjs && node dist/index.mjs"]
