import { useState, useEffect } from "react";
import AdminLayout from "@/components/layout/AdminLayout";
import { apiFetch } from "@/lib/api";
import { Bell, Calendar, Loader2, Sparkles } from "lucide-react";

export default function AdminNotifications() {
  const [notifications, setNotifications] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [notifError, setNotifError] = useState("");

  const loadNotifs = async () => {
    setIsLoading(true);
    setNotifError("");
    try {
      const data = await apiFetch<any[]>("/api/admin/notifications");
      setNotifications(data || []);
    } catch (e: any) {
      setNotifError(e.message || "Failed to load notifications.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadNotifs();
  }, []);

  return (
    <AdminLayout>
      <div className="space-y-8 max-w-4xl mx-auto relative">
        {/* Header */}
        <div className="pb-6 border-b border-zinc-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4 relative z-10">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-violet-500/10 border border-violet-500/30 text-violet-400 text-xs font-black uppercase tracking-wider mb-2">
              <Sparkles className="w-3.5 h-3.5" /> Event Stream
            </div>
            <h1 className="text-2xl md:text-3xl font-black uppercase tracking-tight bg-gradient-to-r from-violet-400 via-cyan-300 to-emerald-400 bg-clip-text text-transparent">
              Operations Center Alerts
            </h1>
            <p className="text-xs text-zinc-400 mt-1">All client notifications generated by admin actions and system events</p>
          </div>
          <span className="text-[10px] font-black uppercase tracking-wider px-3.5 py-1.5 rounded-full border border-cyan-500/30 bg-cyan-500/10 text-cyan-300">
            {isLoading ? "..." : `${notifications.filter((n) => !n.isRead).length} unread`}
          </span>
        </div>

        <div className="relative z-10">
          <div className="rounded-3xl border border-zinc-800 bg-[#060608] backdrop-blur-xl shadow-2xl p-6 md:p-8">
            {notifError ? (
              <div>
                <div className="text-xs text-red-400 bg-red-500/10 border border-red-500/20 rounded-xl p-3">
                  {notifError}
                </div>
                <button
                  onClick={loadNotifs}
                  className="mt-2 text-[10px] font-black uppercase tracking-wider text-cyan-400 hover:underline cursor-pointer"
                >
                  Retry
                </button>
              </div>
            ) : isLoading ? (
              <div className="flex items-center justify-center py-10">
                <Loader2 className="w-6 h-6 text-cyan-400 animate-spin" />
              </div>
            ) : notifications.length > 0 ? (
              <div className="space-y-3">
                {notifications.map((notif) => (
                  <div
                    key={notif.id}
                    className={`p-4 rounded-2xl border transition-colors flex gap-4 ${
                      notif.isRead
                        ? "border-zinc-800/80 bg-black/60 opacity-60"
                        : "border-violet-500/30 bg-gradient-to-r from-violet-950/20 via-black to-cyan-950/20"
                    }`}
                  >
                    <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${
                      notif.isRead ? "bg-zinc-900 text-zinc-500 border border-zinc-800" : "bg-violet-500/10 text-violet-400 border border-violet-500/20"
                    }`}>
                      <Bell className="w-4 h-4" />
                    </div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-4">
                        <h4 className="text-xs font-black uppercase tracking-wider text-white">
                          {notif.title}
                        </h4>
                        <span className="text-[9px] text-zinc-500 font-mono flex items-center gap-1 shrink-0">
                          <Calendar className="w-3 h-3" />
                          {new Date(notif.createdAt).toLocaleString()}
                        </span>
                      </div>
                      <p className="text-xs text-zinc-300 mt-1 leading-relaxed">{notif.message}</p>
                      <div className="text-[10px] text-cyan-400 mt-1.5 font-mono">
                        → {notif.userEmail}{notif.companyName ? ` · ${notif.companyName}` : ""}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center py-12">
                <Bell className="w-8 h-8 mx-auto text-zinc-600 mb-3 animate-pulse" />
                <p className="text-xs text-zinc-400 font-bold uppercase tracking-wider">No notifications sent</p>
                <p className="text-[10px] text-zinc-500 mt-1">Client notifications will appear here when admin actions generate them.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </AdminLayout>
  );
}