import { useState, useEffect } from "react";
import AdminLayout from "@/components/layout/AdminLayout";
import { apiFetch } from "@/lib/api";
import { Bell, Calendar, Loader2 } from "lucide-react";

export default function AdminNotifications() {
  const [notifications, setNotifications] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [notifError, setNotifError] = useState("");

  const loadNotifs = async () => {
    setIsLoading(true);
    setNotifError("");
    try {
      const data = await apiFetch<any[]>("/api/admin/notifications");
      setNotifications(data || []);
    } catch (e: any) {
      setNotifError(e.message || "Failed to load notifications.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadNotifs();
  }, []);

  return (
    <AdminLayout>
      <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-emerald-200/40 rounded-full blur-[120px] pointer-events-none" />

      {/* Header */}
      <div className="mb-10 pb-6 border-b border-slate-200 flex items-center justify-between relative z-10">
        <div>
          <h1 className="text-2xl font-black uppercase tracking-tight text-slate-900">Operations Center Alerts</h1>
          <p className="text-xs text-slate-500 mt-1">All client notifications generated by admin actions and system events</p>
        </div>
        <span className="text-[10px] font-black uppercase tracking-wider px-3 py-1 rounded-full border border-emerald-200 bg-emerald-50 text-emerald-600">
          {isLoading ? "..." : `${notifications.filter((n) => !n.isRead).length} unread`}
        </span>
      </div>

      <div className="max-w-3xl mx-auto relative z-10">
        <div className="rounded-2xl border border-slate-200 bg-white shadow-xl shadow-slate-200/60 p-6">
          {notifError ? (
            <div>
              <div className="text-xs text-red-600 bg-red-50 border border-red-200 rounded-xl p-3">
                {notifError}
              </div>
              <button
                onClick={loadNotifs}
                className="mt-2 text-[10px] font-black uppercase tracking-wider text-emerald-600 hover:underline cursor-pointer"
              >
                Retry
              </button>
            </div>
          ) : isLoading ? (
            <div className="flex items-center justify-center py-10">
              <Loader2 className="w-6 h-6 text-emerald-600 animate-spin" />
            </div>
          ) : notifications.length > 0 ? (
            <div className="space-y-3">
              {notifications.map((notif) => (
                <div
                  key={notif.id}
                  className={`p-4 rounded-xl border transition-colors flex gap-4 ${
                    notif.isRead
                      ? "border-slate-200 bg-slate-50 opacity-60"
                      : "border-emerald-200 bg-emerald-50/50"
                  }`}
                >
                  <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${
                    notif.isRead ? "bg-slate-100 text-slate-400" : "bg-emerald-600/10 text-emerald-600 border border-emerald-200"
                  }`}>
                    <Bell className="w-4 h-4" />
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between gap-4">
                      <h4 className="text-xs font-black uppercase tracking-wider text-slate-900">
                        {notif.title}
                      </h4>
                      <span className="text-[8px] text-slate-400 font-mono flex items-center gap-1 shrink-0">
                        <Calendar className="w-3 h-3" />
                        {new Date(notif.createdAt).toLocaleString()}
                      </span>
                    </div>
                    <p className="text-xs text-slate-600 mt-1 leading-relaxed">{notif.message}</p>
                    <div className="text-[9px] text-slate-400 mt-1.5 font-mono">
                      → {notif.userEmail}{notif.companyName ? ` · ${notif.companyName}` : ""}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-12">
              <Bell className="w-8 h-8 mx-auto text-slate-300 mb-3 animate-pulse" />
              <p className="text-xs text-slate-500 font-bold uppercase tracking-wider">No notifications sent</p>
              <p className="text-[10px] text-slate-400 mt-1">Client notifications will appear here when admin actions generate them.</p>
            </div>
          )}
        </div>
      </div>
    </AdminLayout>
  );
}