export const ACCOUNT_COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
  "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
  "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
  "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada",
  "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros",
  "Congo (DRC)", "Congo (Republic)", "Costa Rica", "Croatia", "Cuba", "Cyprus",
  "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia",
  "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia",
  "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau",
  "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran",
  "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos",
  "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
  "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
  "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova",
  "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (Burma)",
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger",
  "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau",
  "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
  "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda",
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
  "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal",
  "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
  "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan",
  "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
  "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga",
  "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda",
  "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay",
  "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen",
  "Zambia", "Zimbabwe",
];

export const ACCOUNT_CURRENCIES = [
  "AED — UAE Dirham", "AFN — Afghan Afghani", "ALL — Albanian Lek", "AMD — Armenian Dram",
  "ANG — Netherlands Antillean Guilder", "AOA — Angolan Kwanza", "ARS — Argentine Peso",
  "AUD — Australian Dollar", "AWG — Aruban Florin", "AZN — Azerbaijani Manat",
  "BAM — Bosnian Convertible Mark", "BBD — Barbadian Dollar", "BDT — Bangladeshi Taka",
  "BGN — Bulgarian Lev", "BHD — Bahraini Dinar", "BIF — Burundian Franc",
  "BMD — Bermudian Dollar", "BND — Brunei Dollar", "BOB — Bolivian Boliviano",
  "BRL — Brazilian Real", "BSD — Bahamian Dollar", "BTN — Bhutanese Ngultrum",
  "BWP — Botswana Pula", "BYN — Belarusian Ruble", "BZD — Belize Dollar",
  "CAD — Canadian Dollar", "CDF — Congolese Franc", "CHF — Swiss Franc",
  "CLP — Chilean Peso", "CNY — Chinese Yuan", "COP — Colombian Peso",
  "CRC — Costa Rican Colon", "CUP — Cuban Peso", "CVE — Cape Verdean Escudo",
  "CZK — Czech Koruna", "DJF — Djiboutian Franc", "DKK — Danish Krone",
  "DOP — Dominican Peso", "DZD — Algerian Dinar", "EGP — Egyptian Pound",
  "ERN — Eritrean Nakfa", "ETB — Ethiopian Birr", "EUR — Euro", "FJD — Fijian Dollar",
  "FKP — Falkland Islands Pound", "GBP — British Pound", "GEL — Georgian Lari",
  "GHS — Ghanaian Cedi", "GIP — Gibraltar Pound", "GMD — Gambian Dalasi",
  "GNF — Guinean Franc", "GTQ — Guatemalan Quetzal", "GYD — Guyanese Dollar",
  "HKD — Hong Kong Dollar", "HNL — Honduran Lempira", "HTG — Haitian Gourde",
  "HUF — Hungarian Forint", "IDR — Indonesian Rupiah", "ILS — Israeli New Shekel",
  "INR — Indian Rupee", "IQD — Iraqi Dinar", "IRR — Iranian Rial", "ISK — Icelandic Krona",
  "JMD — Jamaican Dollar", "JOD — Jordanian Dinar", "JPY — Japanese Yen",
  "KES — Kenyan Shilling", "KGS — Kyrgyzstani Som", "KHR — Cambodian Riel",
  "KMF — Comorian Franc", "KPW — North Korean Won", "KRW — South Korean Won",
  "KWD — Kuwaiti Dinar", "KYD — Cayman Islands Dollar", "KZT — Kazakhstani Tenge",
  "LAK — Lao Kip", "LBP — Lebanese Pound", "LKR — Sri Lankan Rupee",
  "LRD — Liberian Dollar", "LSL — Lesotho Loti", "LYD — Libyan Dinar",
  "MAD — Moroccan Dirham", "MDL — Moldovan Leu", "MGA — Malagasy Ariary",
  "MKD — Macedonian Denar", "MMK — Myanmar Kyat", "MNT — Mongolian Tugrik",
  "MOP — Macanese Pataca", "MRU — Mauritanian Ouguiya", "MUR — Mauritian Rupee",
  "MVR — Maldivian Rufiyaa", "MWK — Malawian Kwacha", "MXN — Mexican Peso",
  "MYR — Malaysian Ringgit", "MZN — Mozambican Metical", "NAD — Namibian Dollar",
  "NGN — Nigerian Naira", "NIO — Nicaraguan Cordoba", "NOK — Norwegian Krone",
  "NPR — Nepalese Rupee", "NZD — New Zealand Dollar", "OMR — Omani Rial",
  "PAB — Panamanian Balboa", "PEN — Peruvian Sol", "PGK — Papua New Guinean Kina",
  "PHP — Philippine Peso", "PKR — Pakistani Rupee", "PLN — Polish Zloty",
  "PYG — Paraguayan Guarani", "QAR — Qatari Riyal", "RON — Romanian Leu",
  "RSD — Serbian Dinar", "RUB — Russian Ruble", "RWF — Rwandan Franc",
  "SAR — Saudi Riyal", "SBD — Solomon Islands Dollar", "SCR — Seychellois Rupee",
  "SDG — Sudanese Pound", "SEK — Swedish Krona", "SGD — Singapore Dollar",
  "SHP — Saint Helena Pound", "SLL — Sierra Leonean Leone", "SOS — Somali Shilling",
  "SRD — Surinamese Dollar", "SSP — South Sudanese Pound", "STN — Sao Tome and Principe Dobra",
  "SVC — Salvadoran Colon", "SYP — Syrian Pound", "SZL — Swazi Lilangeni",
  "THB — Thai Baht", "TJS — Tajikistani Somoni", "TMT — Turkmenistani Manat",
  "TND — Tunisian Dinar", "TOP — Tongan Pa'anga", "TRY — Turkish Lira",
  "TTD — Trinidad and Tobago Dollar", "TWD — New Taiwan Dollar", "TZS — Tanzanian Shilling",
  "UAH — Ukrainian Hryvnia", "UGX — Ugandan Shilling", "USD — US Dollar",
  "UYU — Uruguayan Peso", "UZS — Uzbekistani Som", "VES — Venezuelan Bolivar",
  "VND — Vietnamese Dong", "VUV — Vanuatu Vatu", "WST — Samoan Tala",
  "XAF — Central African CFA Franc", "XCD — East Caribbean Dollar",
  "XOF — West African CFA Franc", "XPF — CFP Franc", "YER — Yemeni Rial",
  "ZAR — South African Rand", "ZMW — Zambian Kwacha", "ZWL — Zimbabwean Dollar",
];
